#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:

  application:
    # 应用名称
    name: ${rootArtifactId}

  profiles:
    active: dev

  mvc:
    converters:
      # spring mvc使用的json转换器，使用规约指定的gson
      # jackson JacksonHttpMessageConvertersConfiguration
      # gson GsonHttpMessageConvertersConfiguration
      preferred-json-mapper: jackson

  data:
    # redis连接配置
    redis:
      # 替换为redis {host}
      host: {host}
      # 替换为redis {port}
      port: {port}
      # 替换为redis {password}
      password: {password}

  # mysql连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 替换为mysql {host}、{port}、{database}
    url: jdbc:mysql://{host}:{port}/{database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=3000&socketTimeout=3000&useSSL=false
    # 替换为mysql {username}
    username: {username}
    # 替换为mysql {password}
    password: {password}

  config:
    # NacosConfigDataMissingEnvironmentPostProcessor
    # 指定nacos使用配置文件的dataId
    import: 'nacos:${spring.application.name}.yml'

  cloud:
    discovery:
      # 当这个选项被启用后nacos的loadbalancer将会被激活
      # @ConditionalOnDiscoveryEnabled
      enabled: true
    # nacos配置，注意另外需配置spring.cloud.config.import
    nacos:
      # NacosConfigProperties
      config:
        server-addr: vps-nacos:8848
        namespace: ${spring.profiles.active}
      # NacosDiscoveryProperties
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}

    loadbalancer:
      nacos:
        # 启用nacos的loadbalancer
        # @ConditionalOnLoadBalancerNacos
        enabled: true

    # openfeign配置
    openfeign:
      okhttp:
        # OkHttpFeignConfiguration
        enabled: true
      # FeignHttpClientProperties
      httpclient:
        # 关闭ssl验证
        disable-ssl-validation: true
      # FeignClientProperties
      client:
        # FeignClientConfiguration
        config:
          # default表示默认，或者具体的服务名表示指定服务
          default:
            loggerLevel: NONE
            connect-timeout: 3000
            read-timeout: 3000
            follow-redirects: true

server:
  port: 8080
  # Compression
  compression:
    # 启用gzip压缩
    enabled: true

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,offline,online"

# 日志配置
logging:
  level:
    root: info

# 规约配置
convention:
  snowflake-id:
    # 雪花id开始时间，固定不可变
    initial-timestamp: 1702214261706

  i18n:
    # i18n properties文件名称
    base-name: string
    # 使用语言
    locale: zh_CN

  code:
    i18n:
      # 错误码i18n语言，与i18n.locale保持一致
      locale: ${convention.i18n.locale}

# springdoc配置，如需使用同时要启用pom.xml文件中的springdoc-openapi-starter-webmvc-ui依赖
#springdoc:
#
#  swagger-ui:
#    path: /swagger-ui.html
#
#  api-docs:
#    path: /api-docs
#    enabled: true
