#!/bin/bash

script_home=$(readlink -f $(dirname $(readlink -f "$0")))
app_home=$(readlink -f $(dirname $script_home))
# 查找app java环境所在的目录
app_java_home="$APP_JAVA_HOME"
if [ -z "$app_java_home" ]; then
  app_java_home="$JAVA_HOME"
fi
if [ ! -d "$app_java_home" ]; then
  echo "cannot found app_java_home: $app_java_home"
  exit 1
fi
# 查找java命令
app_java_cmd="$app_java_home/bin/java"
if [ ! -x "$app_java_cmd" ]; then
  echo "cannot found app_java_cmd: $app_java_cmd"
  exit 1
fi
# 设置java环境
export JAVA_HOME=$app_java_home
# 获取日志路径
app_runtime_home=$APP_RUNTIME_HOME
if [ -z "$app_runtime_home" ]; then
    app_runtime_home=$app_home
fi

env() {
  echo "script_home: $script_home"
  echo "app_home: $app_home"
  echo "app_java_home: $app_java_home"
  echo "app_java_cmd: $app_java_cmd"
  echo "app_runtime_home: $app_runtime_home"
}

build() {
  set -e
  cd $app_home
  mvn clean install
}

pid() {
  app_pid=$(cat $app_runtime_home/app.pid 2>/dev/null)
  echo "$app_pid"
}

stop() {
  set -e
  app_pid=$(cat $app_runtime_home/app.pid 2>/dev/null)
  if [ -n "$app_pid" ]; then
    kill $app_pid
    rm -f $app_runtime_home/app.pid
  fi
}

start() {
  set -e
  trap stop SIGINT SIGQUIT SIGTERM
  nohup $app_java_cmd -Xms128M -Xmx512M -jar $app_home/web/target/*.jar --spring.profiles.active=prod --logging.path=$app_runtime_home/logs >>$app_runtime_home/logs/console.log 2>&1 &
  app_pid=$!
  echo $app_pid > $app_runtime_home/app.pid
}

help() {
  echo "Usage: $0 {env|build|start|stop|await}"
}

case "$1" in
  'env')
    env
    ;;
  'build')
    build
    ;;
  'start')
    start
    ;;
  'stop')
    stop
    ;;
  'pid')
    pid
    ;;
  *)
    help
    ;;
esac
