#!/bin/bash

script_home=$(readlink -f $(dirname $(readlink -f "$0")))
app_home=$(readlink -f $(dirname $script_home))
# 查找app java环境所在的目录
java_home="$JAVA_HOME"
if [ ! -d "$java_home" ]; then
  echo "cannot found java_home: $java_home"
  exit 1
fi
# 查找java命令
java_cmd="$java_home/bin/java"
if [ ! -x "$java_cmd" ]; then
  echo "cannot found executable java_cmd: $java_cmd"
  exit 1
fi
# 设置java环境
export JAVA_HOME=$java_home
# 获取日志路径
app_runtime_home=$APP_RUNTIME_HOME
if [ -z "$app_runtime_home" ]; then
    app_runtime_home=$app_home
fi

env() {
  echo "script_home: $script_home"
  echo "app_home: $app_home"
  echo "app_runtime_home: $app_runtime_home"
  echo "java_home: $java_home"
  echo "java_cmd: $java_cmd"
}

build() {
  set -e
  cd $app_home
  mvn clean install
}

pid() {
  app_pid=$(cat $app_runtime_home/app.pid 2>/dev/null)
  echo "$app_pid"
}

stop() {
  set -e
  app_pid=$(cat $app_runtime_home/app.pid 2>/dev/null)
  if [ -n "$app_pid" ]; then
    kill $app_pid
    rm -f $app_runtime_home/app.pid
  fi
}

start() {
  set -e
  trap stop SIGINT SIGQUIT SIGTERM
  debug="$DEBUG"
  if [ "$debug" == "true" ]; then
    debug='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:10000'
  fi
  nohup $java_cmd -Xms64M -Xmx256M $debug -jar $app_home/web/target/*.jar --spring.profiles.active=prod --logging.path=$app_runtime_home/logs >>$app_runtime_home/logs/console.log 2>&1 &
  app_pid=$!
  echo $app_pid > $app_runtime_home/app.pid
}

help() {
  echo "Usage: $0 {env|build|start|stop|await}"
}

case "$1" in
  'env')
    env
    ;;
  'build')
    build
    ;;
  'start')
    start
    ;;
  'stop')
    stop
    ;;
  'pid')
    pid
    ;;
  *)
    help
    ;;
esac
